#!/bin/zsh
set -eu -o pipefail
setopt extendedglob nullglob

for dir in templates/*; do
	name=$dir:t
	print "## $name"
	file_list=(
		$dir/template.yaml
		$dir/*~$dir/template.yaml~$dir/result.txt
	)
	print '### Templates'
	for f in $file_list; do
		print "#### \`$f:t\`"
		print '```'
		cat $f
		print '```'
	done
	print '### Jobs created'
	sed 's/.*/- `&`/' $dir/result.txt
done

