#!/bin/zsh
set -eu -o pipefail
setopt extendedglob nullglob

cat <<EOF
# JJB gotchas
Examples of confusing behavior of [Jenkins Job Builder](https://jenkins-job-builder.readthedocs.io/en/latest/).
EOF

print '```'
print '$ jenkins-jobs --version'
$JJB --version
print '```'

for dir in templates/*; do
	print "## Example \`$dir\`"
	file_list=(
		$dir/template.yaml
		$dir/*~$dir/template.yaml~$dir/result.txt
	)
	print '### Templates'
	for f in $file_list; do
		print "#### \`$f:t\`"
		print '```'
		cat $f
		print '```'
	done
	print '### Jobs created'
	sed 's/.*/- `&`/' $dir/result.txt
done

